language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo test
  - cargo doc
after_success:
  - travis-cargo --only nightly doc-upload
notifications:
  email:
    on_success: never
os:
  - linux
  - osx
