[package]
name = "serial-mio"
version = "0.1.0"
license = "MIT"
authors = ["Tae-il Lim <trlim@iotok.kr>"]
description = "Extends serial-rs for mio"
homepage = "https://github.com/trlim/serial-mio"
repository = "https://github.com/trlim/serial-mio"
keywords = ["mio", "serial"]

[dependencies]
serial = "^0.3.2"
mio = "0.5"
